language: node_js
cache:
  directories:
    - node_modules
node_js:
  - 'node'
before_script:
  - npm prune
before_deploy:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: dist # Set the builded dist as the folder to deploy
  on:
    branch: master